server:
  port: 80

spring:
  datasource:
    username: root
    password: dongGY1234
    url: jdbc:mysql://rm-2ze7hrkqw885t3696mo.mysql.rds.aliyuncs.com/student_status_management?characterEncoding=utf-8&useSSL=false

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
    platform: mysql
  security:             #默认用户名密码  --集成了cas暂时没用
    user:
      name: asd
      password: 123

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    db-config:
      insert-strategy: not_empty
      update-strategy: not_null
      id-type: assign_id
    # 驼峰下划线转换
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

JWT:
  timeOut: 2
  SecurityKey: dgy



