
spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    db-config:
      insert-strategy: not_empty
      update-strategy: not_null
      id-type: assign_id
    # 驼峰下划线转换
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

JWT:
  timeOut: 2
  SecurityKey: dgy



