spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  freemarker:
    template-loader-path: classpath:/templates/
server:
  servlet:
    # 以/api开头的请求都将被路由到应用程序的API部分进行处理
    context-path: /api
    encoding:
      force-response: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    db-config:
      insert-strategy: not_empty
      update-strategy: not_null
      id-type: assign_id
      # 驼峰下划线转换
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# jwt创建 超时时间 和 密钥
jwt:
  securityKey: dongyyds
  #jwt token的头
  header: Authorization
  #token存储在redis的有效时间,登录失效时间-秒,多长时间不操作token,需要用刷新token来重新生成登录token秒.值设置的越小，统计在线人数就越精确，但是调用刷新token的请求也会越频繁
  AccessExpireTime: 300
  #refreshToken存储在redis的存在时间,刷新token过期时间-秒，jwt校验时间是这个2倍
  refreshExpireTime: 10800
  #是否允许一个账号多个设备登录,如果为 false,一个账号登录后会自动踢出已经登录的账号
  multipleLogin: true


# 微信登录
weixin:
  mp:
    app-id: wxc2504a5dc7fddcfd
    app-secret: db4bbad1ca7fcd5ec7e5c424d443d339

diboot:
  core:
    init-sql: false

