spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    db-config:
      insert-strategy: not_empty
      update-strategy: not_null
      id-type: assign_id
    # 驼峰下划线转换
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# jwt创建 超时时间 和 密钥
JWT:
  timeOut: 2000
  SecurityKey: dgy
  #是否允许一个账号多个设备登录,如果为false,一个账号登录后会自动踢出已经登录的账号
  multipleLogin: true

# 微信登录
weixin:
  mp:
    app-id: wxc2504a5dc7fddcfd
    app-secret: db4bbad1ca7fcd5ec7e5c424d443d339

diboot:
  core:
    init-sql: false
